<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJlXAmzg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJlXAmzg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJlXAmzg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJlXAmzg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJlXAmzg\App_KernelProdContainer([
    'container.build_hash' => 'JlXAmzg',
    'container.build_id' => '3f468f0d',
    'container.build_time' => 1585491377,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJlXAmzg');
