<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRFjLvSd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRFjLvSd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRFjLvSd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRFjLvSd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRFjLvSd\App_KernelDevDebugContainer([
    'container.build_hash' => 'RFjLvSd',
    'container.build_id' => '6c547d0a',
    'container.build_time' => 1585833406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRFjLvSd');
