<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9mfi72s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9mfi72s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9mfi72s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9mfi72s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9mfi72s\App_KernelDevDebugContainer([
    'container.build_hash' => '9mfi72s',
    'container.build_id' => 'e0750279',
    'container.build_time' => 1585316021,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9mfi72s');
