<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVfWBK9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVfWBK9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVfWBK9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVfWBK9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXVfWBK9\App_KernelDevDebugContainer([
    'container.build_hash' => 'XVfWBK9',
    'container.build_id' => 'bac9280d',
    'container.build_time' => 1586019436,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVfWBK9');
